const $=s=>document.querySelector(s),screens=['home','lobby','game'];let session=null,state=null,source=null,selected=new Set();
const names={1:'대 달무티',2:'대주교',3:'원수',4:'남작부인',5:'수도원장',6:'기사',7:'재봉사',8:'석공',9:'요리사',10:'양치기',11:'석공 노동자',12:'농노',13:'광대'};
function show(id){screens.forEach(x=>$('#'+x).classList.toggle('hidden',x!==id))}
function toast(m){const t=$('#toast');t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2300)}
async function act(type,data={}){try{const payload={type,...(session||{}),...data};const r=await fetch('/api/action',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const j=await r.json();if(!j.ok)throw Error(j.error);if(j.session){session=j.session;localStorage.setItem('dalmuti-session',JSON.stringify(session))}if(j.state)render(j.state);return true}catch(e){toast(e.message);return false}}
function connect(){if(source)source.close();const q=new URLSearchParams(session);source=new EventSource('/api/events?'+q);source.addEventListener('state',e=>render(JSON.parse(e.data)));source.onerror=()=>{}}
$('#create').onclick=async()=>{session=null;if(await act('create-room',{name:$('#name').value,capacity:Number($('#capacity').value)}))connect()};
$('#join').onclick=async()=>{session=null;if(await act('join-room',{name:$('#name').value,roomCode:$('#roomCode').value}))connect()};
$('#start').onclick=()=>act('start-game');$('#clear').onclick=()=>{selected.clear();render(state)};
document.querySelectorAll('.leave').forEach(b=>b.onclick=async()=>{if(!confirm('방에서 나갈까요? 게임 중에는 자리가 보존되어 같은 닉네임으로 재접속할 수 있습니다.'))return;await act('leave-room');if(source)source.close();source=null;session=null;state=null;selected.clear();localStorage.removeItem('dalmuti-session');show('home')});
document.querySelectorAll('.chatSend').forEach((b,i)=>b.onclick=()=>sendChat(b.parentElement.querySelector('.chatInput')));
document.querySelectorAll('.chatInput').forEach(inp=>inp.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();sendChat(inp)}}));
async function sendChat(inp){const message=inp.value.trim();if(!message)return;if(await act('send-chat',{message}))inp.value=''}
function render(s){state=s;if(!s.room.started)lobby(s);else game(s);renderChat(s.room.chat||[])}
function renderChat(items){const html=items.map(m=>`<div class="chatmsg"><b>${esc(m.name)}</b>${esc(m.text)}</div>`).join('');['#chatLobby','#chatGame'].forEach(sel=>{const el=$(sel);if(!el)return;const near=el.scrollHeight-el.scrollTop-el.clientHeight<35;el.innerHTML=html;if(near||!el.dataset.ready)el.scrollTop=el.scrollHeight;el.dataset.ready='1'})}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function lobby(s){show('lobby');$('#code').textContent=s.room.code;$('#count').textContent=`${s.room.players.length} / ${s.room.capacity}`;$('#lobbyPlayers').innerHTML=s.room.players.map((p,i)=>`<div class="person"><span>${i+1}. ${esc(p.name)}${p.id===s.room.hostId?' 👑':''}</span><span>${p.connected?'접속':'끊김'}</span></div>`).join('');$('#start').classList.toggle('hidden',s.viewerId!==s.room.hostId);$('#start').disabled=s.room.players.length!==s.room.capacity}
function card(c,clickable=true){return `<button class="card ${c.rank===13?'jester':''} ${selected.has(c.id)?'selected':''}" data-id="${c.id}" ${clickable?'':'disabled'}><span class="num">${c.rank===13?'★':c.rank}</span><span class="name">${names[c.rank]}</span></button>`}
function game(s){show('game');const g=s.game,me=g.players.find(p=>p.id===s.viewerId),cur=g.players.find(p=>p.id===g.currentPlayerId);$('#handNo').textContent=`${g.handNumber}번째 판`;$('#phase').textContent=phaseName(g.phase);$('#roomBadge').textContent=s.room.code;$('#status').textContent=statusText(g,me,cur);$('#players').innerHTML=[...g.players].sort((a,b)=>a.roleIndex-b.roleIndex).map(p=>`<div class="player ${p.id===g.currentPlayerId?'turn':''} ${p.id===me.id?'me':''}"><div class="role">${p.role}</div><div class="pname">${esc(p.name)}${p.id===me.id?' (나)':''}</div><div class="pmeta">${p.handCount}장${p.finishPlace?` · ${p.finishPlace}위`:''}${p.connected?'':' · 끊김'}</div></div>`).join('');$('#pileOwner').textContent=g.pile?`— ${g.pile.playerName} 제출`:'';$('#pile').className='pile'+(g.pile?'':' empty');$('#pile').innerHTML=g.pile?g.pile.cards.map(c=>card({id:'',rank:c.rank},false)).join(''):'새 묶음';$('#handCount').textContent=`${me.hand.length}장`;$('#hand').innerHTML=me.hand.map(c=>card(c)).join('');$('#hand').querySelectorAll('.card').forEach(b=>b.onclick=()=>{const id=b.dataset.id;selected.has(id)?selected.delete(id):selected.add(id);render(state)});$('#logs').innerHTML=[...g.logs].reverse().map(x=>`<div>${esc(x)}</div>`).join('');actions(g,me)}
function phaseName(p){return({revolution:'혁명 선언',tax:'세금',play:'카드 내기',results:'판 종료'})[p]||p}
function statusText(g,me,cur){if(g.phase==='revolution')return g.tax.eligibleForViewer&&!g.tax.declined?'광대 2장으로 혁명을 선언할 수 있습니다.':'혁명 선언 여부를 기다리는 중입니다.';if(g.phase==='tax')return g.currentPlayerId===me.id?'농노에게 돌려줄 카드를 선택하세요.':`${cur?.name||''}이(가) 세금을 처리하는 중입니다.`;if(g.phase==='play')return cur?.id===me.id?'내 차례입니다.':'현재 '+(cur?.name||'')+'의 차례입니다.';if(g.phase==='results')return `${g.players.find(p=>p.id===g.winnerId)?.name}이(가) 새 대 달무티입니다!`;return''}
function actions(g,me){const a=$('#actions');let h='';if(g.phase==='revolution'&&g.tax.eligibleForViewer&&!g.tax.declined){h+=`<button data-a="rev" class="primary">혁명 선언</button>`;if(me.role==='대 농노')h+=`<button data-a="great" class="primary">대혁명 선언</button>`;h+=`<button data-a="decline">혁명하지 않기</button>`}else if(g.phase==='tax'&&g.currentPlayerId===me.id){h=`<button data-a="tax" class="primary">선택한 ${g.tax.pending.count}장 돌려주기</button>`}else if(g.phase==='play'&&g.currentPlayerId===me.id){h=`<button data-a="play" class="primary">선택한 카드 내기</button>${g.pile?'<button data-a="pass">패스</button>':''}`}else if(g.phase==='results'&&me.role==='대 달무티')h=`<button data-a="next" class="primary">다음 판 시작</button>`;a.innerHTML=h;a.querySelectorAll('button').forEach(b=>b.onclick=async()=>{const ids=[...selected],x=b.dataset.a;if(x==='rev')act('declare-revolution',{greater:false});if(x==='great')act('declare-revolution',{greater:true});if(x==='decline')act('decline-revolution');if(x==='tax'){if(await act('tax-return',{cardIds:ids}))selected.clear()}if(x==='play'){if(await act('play-cards',{cardIds:ids}))selected.clear()}if(x==='pass')act('pass');if(x==='next'){if(await act('next-hand'))selected.clear()}})}
(async()=>{try{const x=JSON.parse(localStorage.getItem('dalmuti-session'));if(x){session=x;if(await act('reconnect-session'))connect();else localStorage.removeItem('dalmuti-session')}}catch{localStorage.removeItem('dalmuti-session')}})();
